# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0002_team_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='progress',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='team',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
