# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0003_auto_20171103_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
