# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0006_auto_20171103_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='comments',
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.CharField(default='...', max_length=2000),
        ),
    ]
