# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 12:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0010_auto_20171103_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
