# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 12:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0011_auto_20171103_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number is invalid. Enter up to 10 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
