# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 13:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0012_auto_20171103_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Please describe the project here.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number is invalid. Enter up to 10 digits.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
