# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0013_auto_20171103_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
