# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0014_auto_20171103_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leader',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=20),
        ),
    ]
