# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0015_auto_20171103_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='join_date',
        ),
    ]
