# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0016_remove_employee_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
