# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0021_remove_employee_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pas.Project'),
        ),
    ]
