# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0022_resource_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.CharField(default='Default Comment', max_length=2000),
        ),
    ]
