# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0024_auto_20171105_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.CharField(blank=True, default='Default Comment', max_length=2000, null=True),
        ),
    ]
