# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0026_project_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(),
        ),
    ]
