# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0027_auto_20171105_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='budget',
            field=models.IntegerField(default=10000),
        ),
    ]
