# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0029_auto_20171105_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pas.Department'),
            preserve_default=False,
        ),
    ]
