# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0030_panel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, default='Default Topic', max_length=2000, null=True),
        ),
    ]
