# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0032_auto_20171107_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pas.Team'),
        ),
    ]
